version: '3'
services:
 node-app:
   container_name: expressapp2
   volumes:
     - ./src:/app/src:ro
   ports:
    - "3000:3000"
   environment: 
    - ./.env
   depends_on:
    - mongo


 mongo:
   image: mongo:6.0.4
   restart: always
   environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example




 nginx:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
       - node-app
     



volumes:
  mongo-db:
